### ISSUE TITLE
File System

### ISSUE THREAD

**Issue by RAWJUNGLE** [democloid/picoTracker#76] opened 2024-01-09 17:28 UTC
Again problems with the file system, the samples that used to work and displayed in the menu are partially gone. Some samples are simply not played. Also, I have the impression that not the whole memory is loaded with samples, but partially.

I recommend that you try working with samples of different lengths.

In some cases, you will hear a memory overload sound. 

And the clock won't work right.

When replacing a file in the sampler, it is not deleted from the project and memory. Perhaps it is necessary to make at least deletion from the project, it will already save flash memory.

Project file:
https://discord.com/channels/1166483348634480650/1166796422486696086/1194429761091539005

Project size - 1mb 

Audio: (memory overload sound)
https://discord.com/channels/1166483348634480650/1166796422486696086/1194430801299918878

Audio: (deleted track (chain70)clicks gone))
https://discord.com/channels/1166483348634480650/1166796422486696086/1194431887997947996

Even if I load small samples, it is impossible to overcome the 1 mb threshold. it feels like there is a memory limitation somewhere.

**Comment by democloid** [comment] 2024-01-10 03:47
This is probably just a duplicate of #18, pretty easy fix which we should prioritize @maks

**Comment by maks** [comment] 2024-01-10 04:25
@democloid I guess it's just the `FLASH_LIMIT` in https://github.com/democloid/picoTracker/blob/master/sources%2FApplication%2FInstruments%2FWavFile.cpp#L14. ?

**Comment by democloid** [comment] 2024-01-10 04:33
@maks yes, that's it. I have a patch already tested and working, will submit a PR a bit later today

**Comment by democloid** [comment] 2024-02-08 03:00
this is done

**Closed** 2024-02-08 03:01 UTC
